---
title: "End of chapter 4"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Calculate 5 number summary
```{r cereal}
cereals.df <- read.csv("Cereals.csv") 
sapply(cereals.df, mean, na.rm=TRUE)
sapply(cereals.df[,-c(1:3)], sd, na.rm=TRUE)
sapply(cereals.df[,-c(1:3)], median, na.rm=TRUE)
sapply(cereals.df[,-c(1:3)], min, na.rm=TRUE)
sapply(cereals.df[,-c(1:3)], max, na.rm=TRUE)
```

Create histogram for variables
```{r}
install.packages("psych")
library(psych)
multi.hist(cereals.df[,-c(1:3)])
```

Side by side box plot
```{r pressure, echo=FALSE}
boxplot(cereals.df$calories~cereals.df$type, horizontal = TRUE)
boxplot(cereals.df$rating~cereals.df$shelf, horizontal = FALSE)
```

Correlation plot
```{r}
library(corrplot)
cc <- cor(na.omit(cereals.df[,-c(1:3)]))
corrplot.mixed(cc, order="hclust", tl.col="black")
corrplot(cc, order="hclust", tl.col="black")
```

Correlation plot after normalizing data
```{r}
scc <- cor(scale(na.omit(cereals.df[,-c(1:3)])))
corrplot(scc, order="hclust", tl.col="black")
```

